version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_library_db
    restart: always
    environment:
      MYSQL_DATABASE: library_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:

# usage:
#  docker-compose up -d

#  docker exec -it mysql_library_db mysql -u root -p

#  USE library_db;
#  SOURCE /path/to/starter-data.sql;
